# Exported from Render on 2025-04-22T20:53:49Z
version: "1"
services:
  - type: web
    name: bebel_api
    runtime: python
    repo: https://github.com/solop56/e-commerce.git
    plan: free
    region: oregon
    buildCommand: cd app && pip install -r ../requirements.txt
    startCommand: cd app && python manage.py migrate && gunicorn ecommerce.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_PORT
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
      - key: ALLOWED_HOSTS
        sync: false

databases:
  - name: bebel_api
    databaseName: bebel_db
    user: bebel_user
    plan: free
