# Exported from Render on 2025-04-22T20:53:49Z
version: "1"
services:
  - type: web
    name: bebel_api
    runtime: python
    repo: https://github.com/solop56/e-commerce.git
    plan: free
    region: oregon
    buildCommand: cd app && pip install -r ../requirements.txt && python manage.py migrate
    startCommand: gunicorn ecommerce.wsgi:application --bind 0.0.0:8000
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: DB_HOST
        fromDatabase:
          name: bebel_api
          property: host
      - key: DB_NAME
        fromDatabase:
          name: bebel_api
          property: database
      - key: DB_USER
        fromDatabase:
          name: bebel_api
          property: user
      - key: DB_PASS
        fromDatabase:
          name: bebel_api
          property: password
      - key: DB_PORT
        fromDatabase:
          name: bebel_api
          property: port
      - key: SECRET_KEY
        generate: true
      - key: DEBUG
        sync: false
      - key: ALLOWED_HOSTS
        value: "e-commerce-1-pdsc.onrender.com"

databases:
  - name: bebel_api
    databaseName: bebel_db
    user: bebel_user
    plan: free
