# Generated by Django 5.2 on 2025-05-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin_user',
            field=models.BooleanField(default=False),
        ),
    ]
