# Generated by Django 5.2 on 2025-05-07 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_user_is_admin_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='features',
            new_name='location',
        ),
    ]
