# Generated by Django 5.2 on 2025-04-21 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Rent',
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rent')),
            ],
        ),
    ]
