# Generated by Django 5.2 on 2025-04-22 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rent'),
        ),
    ]
