# Generated by Django 5.2 on 2025-04-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_date_joined_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
