# Generated by Django 5.2 on 2025-04-28 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='type',
            new_name='property_type',
        ),
    ]
