# Generated by Django 5.2 on 2025-05-01 12:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_type_rent_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_property_image),
        ),
    ]
